//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAdvance.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ApplicationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ApplicationSettings defaultInstance = ((ApplicationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ApplicationSettings())));
        
        public static ApplicationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int DEFAULT_SLEEP_INTERVAL {
            get {
                return ((int)(this["DEFAULT_SLEEP_INTERVAL"]));
            }
            set {
                this["DEFAULT_SLEEP_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chrome.exe")]
        public string DEFAULT_BROWSER_EXE {
            get {
                return ((string)(this["DEFAULT_BROWSER_EXE"]));
            }
            set {
                this["DEFAULT_BROWSER_EXE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("notepad.exe")]
        public string DEFAULT_TEXT_EDITOR {
            get {
                return ((string)(this["DEFAULT_TEXT_EDITOR"]));
            }
            set {
                this["DEFAULT_TEXT_EDITOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Christopher\\Documents\\Visual Studio 2013\\Output.html")]
        public string WEB_EXPORT_PATH {
            get {
                return ((string)(this["WEB_EXPORT_PATH"]));
            }
            set {
                this["WEB_EXPORT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Output.csv")]
        public string FILE_EXPORT_PATH {
            get {
                return ((string)(this["FILE_EXPORT_PATH"]));
            }
            set {
                this["FILE_EXPORT_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238")]
        public int START_AT_ROW {
            get {
                return ((int)(this["START_AT_ROW"]));
            }
            set {
                this["START_AT_ROW"] = value;
            }
        }
    }
}
